  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    abbrv text not null,
    logo_url text null,
    constraint teams_pkey primary key (id),
    constraint teams_name_key unique (name)
  ) tablespace pg_default;

create table
  public.players (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team bigint null,
    position bigint null,
    sleeper_search_rank bigint null,
    sleeper_id bigint null,
    constraint players_pkey primary key (id),
    constraint players_team_fkey foreign key (team) references teams (id),
  ) tablespace pg_default;

  create table
  public.games (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team_one bigint null,
    team_two bigint null,
    constraint games_pkey primary key (id),
    constraint players_team_fkey foreign key (team) references teams (id),
  ) tablespace pg_default;