  create table
  public.leagues (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sport text not null,
    constraint leagues_pkey primary key (id)
  ) tablespace pg_default;  

  
  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    league bigint not null,
    intraleague_details text null,
    abbrv text not null,
    logo_url text null,
    constraint teams_pkey primary key (id),
    constraint teams_league_fkey foreign key (league) references leagues (id)
  ) tablespace pg_default;

create table
  public.players (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team bigint null,
    position bigint null,
    depth_chart_order int null,
    sleeper_search_rank bigint null,
    sleeper_id bigint null,
    constraint players_pkey primary key (id),
    constraint players_team_fkey foreign key (team) references teams (id)
  ) tablespace pg_default;

  create table
  public.games (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team_one bigint null,
    team_two bigint null,
    constraint games_pkey primary key (id),
    constraint players_team_one_fkey foreign key (team_one) references teams (id),
    constraint players_team_two_fkey foreign key (team_two) references teams (id)
  ) tablespace pg_default;

