  create table
  public.leagues (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    sport text not null,
    constraint leagues_pkey primary key (id)
  ) tablespace pg_default;  

  
  create table
  public.teams (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    league bigint not null,
    intraleague_details text null,
    abbrv text not null,
    logo_url text null,
    constraint teams_pkey primary key (id),
    constraint teams_league_fkey foreign key (league) references leagues (id)
  ) tablespace pg_default;

CREATE INDEX idx_teams_abbrv_league
ON teams (abbrv, league);

create table
  public.players (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    team bigint null,
    position text null,
    depth_chart_order int null,
    sleeper_search_rank bigint null,
    sleeper_id bigint null,
    rotowire_id bigint null,
    constraint players_pkey primary key (id),
    constraint players_team_fkey foreign key (team) references teams (id)
  ) tablespace pg_default;

  create table
  public.games (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    season_year bigint not null,
    played_at timestamp null,
    intraseason_indicator text null,
    name text not null,
    team_one bigint null,
    team_two bigint null,
    constraint games_pkey primary key (id),
    constraint players_team_one_fkey foreign key (team_one) references teams (id),
    constraint players_team_two_fkey foreign key (team_two) references teams (id)
  ) tablespace pg_default;

create table
public.nfl_gamelog (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    player bigint not null,
    game bigint not null,
    passing_comp int null,
    passing_att int null,
    passing_yds int null,
    passing_td int null,
    passing_int int null,
    rushing_att int null,
    rushing_yds int null,
    rushing_td int null,
    receiving_rec int null,
    receiving_yds int null,
    receiving_tgt int null,
    receiving_td int null,
    constraint nfl_gamelog_pkey primary key (id),
    constraint nfl_gamelog_games_fkey foreign key (game) references games (id),
    constraint nfl_gamelog_player_fkey foreign key (player) references players (id)
) tablespace pg_default;

CREATE INDEX idx_nfl_gamelog_player_game
ON nfl_gamelog (player, game);
